<h1>This is my template, there are many like it, but this one is mine.</h1>
<script type="text/x-magento-init">
{
  "*": {
    "Magento_Ui/js/core/app": <?php echo $block->getJsLayout(); ?>
  }
}
</script>
<div data-bind="scope: '42'">
  <h3>Scope: '42'</h3>
<span data-bind="text: foo"></span>
</div>
<div id="foobar">
Here comes content...
</div>
<div data-bind="scope: 'sparta2'"><!-- ko template: getTemplate() --><!-- /ko --></div>
<div id="sparta" data-bind="scope: 'sparta'">
  <h2>This is sparta scoped</h2>
  <input type="text" data-bind="attr: {value: answer}"/>
</div>
<script>
require(['ko'/*, 'Magento_Ui/js/lib/knockout/bootstrap'*/], function (ko) {

  function createContent(){
    console.log('Creating content...');
    const div = document.getElementById('foobar');
    div.innerHTML = `
    <div data-bind="scope: 'sparta'">
      <input type="text" data-bind="attr: {placeholder: $t('Pickup location')}" />
      <span data-bind="text: answer"></span>
    </div>
   `;
    ko.cleanNode(div);
    ko.applyBindings(undefined, div);
    console.log('Done!');
  }

  //createContent();

  setTimeout(createContent, 5000);
});
</script>
